### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by alichtman** [gretzky/refind-retina-black#1]

**Comment by gretzky** [comment]
Hey Aaron,

Here's how you do it on macOS. I also have instructions for Arch if you use it.

1. [install rEFInd](https://sourceforge.net/projects/refind/)
2. Unzip and run `./refind-install`
3. Verify it works by restarting. You should see the stock rEFInd boot menu.

To add & configure this theme:

1. Mount rEFInd `sudo mount -t msdos /dev/disk0s1 /Volumes`
2. cd `/Volumes/EFI/rEFInd`
3. Make a themes directory `mkdir -p themes && cd themes`
4. Clone any rEFInd theme you want- in this case, this one: `git clone https://github.com/gretzky/refind-retina-black`
5. `cd ..`
6. Add the theme to refind.conf `echo "include themes/refind-retina-black/theme.conf" >> refind.conf`
7. Edit the refind.conf to include the icons used in the theme
    * Look fore each menuentry and change the icon file path to `/EFI/refind/themes/refind-retina-black/os_whatever.png`

Reboot to verify the theme worked. I've been messing with rEFInd and themes quite a bit lately so if you find any issue let me know.

**Comment by alichtman** [comment]
Awesome, thanks for the walkthrough!

I'll try this out sometime tomorrow.

Would you consider putting these instructions in the README?

**Comment by gretzky** [comment]
Sure thing
